# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeApplicationv0554' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeApplicationv0554
  pod 'AppCenter/Crashes', '~> 1.7.1'
  pod 'AppCenter/Analytics', '~> 1.7.1'
  pod 'AppCenterReactNativeShared', '~> 1.6.0'

  

  platform :ios, '9.0'
  target 'ReactNativeApplicationv0554Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeApplicationv0554-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeApplicationv0554-tvOS

  target 'ReactNativeApplicationv0554-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
